<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('districts')->insert([
        ['id'=>14, 'region_id'=>1,	'name'=>'Andijon shahri'],
['id'=>15, 'region_id'=>1,	'name'=>'Shaxrihon tumani'],
['id'=>16, 'region_id'=>1,	'name'=>'Marxamat tumani'],
['id'=>17, 'region_id'=>1,	'name'=>'Qo‘rg‘ontepa tumani'],
['id'=>18, 'region_id'=>1,	'name'=>'Jalaquduq tumani'],
['id'=>19, 'region_id'=>1,	'name'=>'Xo\'jaobod tumani'],
['id'=>20, 'region_id'=>1,	'name'=>'Xonobod shahri'],
['id'=>21, 'region_id'=>1,	'name'=>'Ulug\'nor tumani'],
['id'=>22, 'region_id'=>1,	'name'=>'Paxtaobod tumani'],
['id'=>23, 'region_id'=>1,	'name'=>'Oltinko\'l tumani'],
['id'=>24, 'region_id'=>1,	'name'=>'Bo\'ston tumani'],
['id'=>25, 'region_id'=>1,	'name'=>'Buloqboshi tumani'],
['id'=>26, 'region_id'=>1,	'name'=>'Andijon tumani'],
['id'=>27, 'region_id'=>1,	'name'=>'Baliqchi tumani'],
['id'=>28, 'region_id'=>1,	'name'=>'Izboskan tumani'],
['id'=>29, 'region_id'=>1,	'name'=>'Asaka tumani'],
['id'=>30, 'region_id'=>2,	'name'=>'Ромитан туман'],
['id'=>31, 'region_id'=>2,	'name'=>'Пешку туман'],
['id'=>32, 'region_id'=>2,	'name'=>'Шофиркон туман'],
['id'=>33, 'region_id'=>2,	'name'=>'Ғиждувон туман'],
['id'=>34, 'region_id'=>2,	'name'=>'Вобкент туман'],
['id'=>35, 'region_id'=>2,	'name'=>'Олот туман'],
['id'=>36, 'region_id'=>2,	'name'=>'Қоракўл туман'],
['id'=>37, 'region_id'=>2,	'name'=>'Жондор туман'],
['id'=>38, 'region_id'=>2,	'name'=>'Қоровулбозор туман'],
['id'=>39, 'region_id'=>2,	'name'=>'Когон туман'],
['id'=>40, 'region_id'=>2,	'name'=>'Когон шаҳар'],
['id'=>41, 'region_id'=>2,	'name'=>'Бухоро туман'],
['id'=>42, 'region_id'=>2,	'name'=>'Бухоро шахар'],
['id'=>43, 'region_id'=>3,	'name'=>'Фарғона шахар'],
['id'=>44, 'region_id'=>3,	'name'=>'Cўх тумани'],
['id'=>45, 'region_id'=>3,	'name'=>'Фарғона тумани'],
['id'=>46, 'region_id'=>3,	'name'=>'Учкўприк тумани'],
['id'=>47, 'region_id'=>3,	'name'=>'Ўзбекистон тумани'],
['id'=>48, 'region_id'=>3,	'name'=>'Тошлоқ тумани'],
['id'=>49, 'region_id'=>3,	'name'=>'Фурқат тумани'],
['id'=>50, 'region_id'=>3,	'name'=>'Риштон тумани'],
['id'=>51, 'region_id'=>3,	'name'=>'Қўштепа тумани'],
['id'=>52, 'region_id'=>3,	'name'=>'Қува тумани'],
['id'=>53, 'region_id'=>3,	'name'=>'Ёзёвон тумани'],
['id'=>54, 'region_id'=>3,	'name'=>'Данғара тумани'],
['id'=>55, 'region_id'=>3,	'name'=>'Бувайда тумани'],
['id'=>56, 'region_id'=>3,	'name'=>'Бағдод тумани'],
['id'=>57, 'region_id'=>3,	'name'=>'Олтиариқ тумани'],
['id'=>58, 'region_id'=>3,	'name'=>'Бешариқ тумани'],
['id'=>59, 'region_id'=>3,	'name'=>'Қўқон шаҳар'],
['id'=>60, 'region_id'=>3,	'name'=>'Қувасой шаҳар'],
['id'=>61, 'region_id'=>3,	'name'=>'Марғилон шаҳар'],
['id'=>62, 'region_id'=>4,	'name'=>'Jizzax shahri'],
['id'=>63, 'region_id'=>4,	'name'=>'Yangiobod tumani'],
['id'=>64, 'region_id'=>4,	'name'=>'Sh.Rashidov tumani'],
['id'=>65, 'region_id'=>4,	'name'=>'Forish tumani'],
['id'=>66, 'region_id'=>4,	'name'=>'Paxtakor tumani'],
['id'=>67, 'region_id'=>4,	'name'=>'Mirzacho\'l tumani'],
['id'=>68, 'region_id'=>4,	'name'=>'Zomin tumani'],
['id'=>69, 'region_id'=>4,	'name'=>'Zafarobod tumani'],
['id'=>70, 'region_id'=>4,	'name'=>'Zarbdor tumani'],
['id'=>71, 'region_id'=>4,	'name'=>'Do\'stlik tumani'],
['id'=>72, 'region_id'=>4,	'name'=>'G\'allaorol tumani'],
['id'=>73, 'region_id'=>4,	'name'=>'Baxmal tumani'],
['id'=>74, 'region_id'=>4,	'name'=>'Arnasoy tumani'],
['id'=>75, 'region_id'=>5,	'name'=>'Тўрақўрғон тумани'],
['id'=>76, 'region_id'=>5,	'name'=>'Мингбулоқ тумани'],
['id'=>77, 'region_id'=>5,	'name'=>'Янгиқўрғон тумани'],
['id'=>78, 'region_id'=>5,	'name'=>'Наманган тумани'],
['id'=>79, 'region_id'=>5,	'name'=>'Янги наманган туман'],
['id'=>80, 'region_id'=>5,	'name'=>'Косонсой туман'],
['id'=>81, 'region_id'=>5,	'name'=>'Чуст туман'],
['id'=>82, 'region_id'=>5,	'name'=>'Учқўрғон туман'],
['id'=>83, 'region_id'=>5,	'name'=>'Поп туман'],
['id'=>84, 'region_id'=>5,	'name'=>'Уйчи туман'],
['id'=>85, 'region_id'=>5,	'name'=>'Чортоқ туман'],
['id'=>86, 'region_id'=>5,	'name'=>'Наманган шахар'],
['id'=>87, 'region_id'=>5,	'name'=>'Норин туман'],
['id'=>88, 'region_id'=>5,	'name'=>'Давлатобод туман'],
['id'=>89, 'region_id'=>6,	'name'=>'Хатирчи тумани'],
['id'=>90, 'region_id'=>6,	'name'=>'Томди тумани'],
['id'=>91, 'region_id'=>6,	'name'=>'Нурота тумани'],
['id'=>92, 'region_id'=>6,	'name'=>'Навоий шаҳар'],
['id'=>93, 'region_id'=>6,	'name'=>'Навбаҳор тумани'],
['id'=>94, 'region_id'=>6,	'name'=>'Қизилтепа тумани'],
['id'=>95, 'region_id'=>6,	'name'=>'Конимех тумани'],
['id'=>96, 'region_id'=>6,	'name'=>'Кармана тумани'],
['id'=>97, 'region_id'=>6,	'name'=>'Зарафшон шаҳар'],
['id'=>98, 'region_id'=>6,	'name'=>'Ғозғон шаҳар'],
['id'=>99, 'region_id'=>7,	'name'=>'Chiroqchi tuman'],
['id'=>100, 'region_id'=>7,	'name'=>'Qamashi tuman'],
['id'=>101, 'region_id'=>7,	'name'=>'G\'uzor tuman'],
['id'=>102, 'region_id'=>7,	'name'=>'Ko\'kdala tuman'],
['id'=>103, 'region_id'=>7,	'name'=>'Nishon tuman'],
['id'=>104, 'region_id'=>7,	'name'=>'Yakkabog\' tuman'],
['id'=>105, 'region_id'=>7,	'name'=>'Dehqonobod tumani'],
['id'=>106, 'region_id'=>7,	'name'=>'Mirishkor tuman'],
['id'=>107, 'region_id'=>7,	'name'=>'Qarshi tuman'],
['id'=>108, 'region_id'=>7,	'name'=>'Shahrisabz Shahar'],
['id'=>109, 'region_id'=>7,	'name'=>'Shahrisabz tumani'],
['id'=>110, 'region_id'=>7,	'name'=>'Kitob tumani'],
['id'=>111, 'region_id'=>7,	'name'=>'Muborak tumani'],
['id'=>112, 'region_id'=>7,	'name'=>'Kasbi tuman'],
['id'=>113, 'region_id'=>7,	'name'=>'Koson tuman'],
['id'=>114, 'region_id'=>7,	'name'=>'Qarshi shahar'],
['id'=>115, 'region_id'=>9,	'name'=>'Samarqand shaxar'],
['id'=>116, 'region_id'=>9,	'name'=>'Urgut tumani'],
['id'=>117, 'region_id'=>9,	'name'=>'Tayloq tumani'],
['id'=>118, 'region_id'=>9,	'name'=>'Samarqand tumani'],
['id'=>119, 'region_id'=>9,	'name'=>'Paxtachi tumani'],
['id'=>120, 'region_id'=>9,	'name'=>'Pastdarg\'om tumani'],
['id'=>121, 'region_id'=>9,	'name'=>'Payariq tumani'],
['id'=>122, 'region_id'=>9,	'name'=>'Nurobot tumani'],
['id'=>123, 'region_id'=>9,	'name'=>'Narpay tumani'],
['id'=>124, 'region_id'=>9,	'name'=>'Qushrabot tumani'],
['id'=>125, 'region_id'=>9,	'name'=>'Kattaqurg\'on tumani'],
['id'=>126, 'region_id'=>9,	'name'=>'Ishtixon tumani'],
['id'=>127, 'region_id'=>9,	'name'=>'Jomboy tumani'],
['id'=>128, 'region_id'=>9,	'name'=>'Bulung\'ur tumani'],
['id'=>129, 'region_id'=>9,	'name'=>'Kattaqurg\'on shaxar'],
['id'=>130, 'region_id'=>9,	'name'=>'Oqdaryo tumani'],
['id'=>131, 'region_id'=>11,	'name'=>'Бандихон туман'],
['id'=>132, 'region_id'=>11,	'name'=>'Қизириқ туман'],
['id'=>133, 'region_id'=>11,	'name'=>'Сариосиё туман'],
['id'=>134, 'region_id'=>11,	'name'=>'Узун туман'],
['id'=>135, 'region_id'=>11,	'name'=>'Олтинсой туман'],
['id'=>136, 'region_id'=>11,	'name'=>'Денов туман'],
['id'=>137, 'region_id'=>11,	'name'=>'Шўрчи туман'],
['id'=>138, 'region_id'=>11,	'name'=>'Қумқўрғон туман'],
['id'=>139, 'region_id'=>11,	'name'=>'Жарқўрғон туман'],
['id'=>140, 'region_id'=>11,	'name'=>'Бойсун туман'],
['id'=>141, 'region_id'=>11,	'name'=>'Шеробод туман'],
['id'=>142, 'region_id'=>11,	'name'=>'Музработ туман'],
['id'=>143, 'region_id'=>11,	'name'=>'Ангор туман'],
['id'=>144, 'region_id'=>11,	'name'=>'Термиз туман'],
['id'=>145, 'region_id'=>11,	'name'=>'Термиз шаҳар'],
['id'=>146, 'region_id'=>12,	'name'=>'Nurafshon shahar'],
['id'=>147, 'region_id'=>12,	'name'=>'Yangiyo‘l shahar'],
['id'=>148, 'region_id'=>12,	'name'=>'Yangiyo‘l tumani'],
['id'=>149, 'region_id'=>12,	'name'=>'Chinoz tumani'],
['id'=>150, 'region_id'=>12,	'name'=>'Chirchiq shahar'],
['id'=>151, 'region_id'=>12,	'name'=>'Quychirchiq tumani'],
['id'=>152, 'region_id'=>12,	'name'=>'Yuqorichirchiq tumani'],
['id'=>153, 'region_id'=>12,	'name'=>'O‘rtachirchiq tumani'],
['id'=>154, 'region_id'=>12,	'name'=>'Toshkent tumani'],
['id'=>155, 'region_id'=>12,	'name'=>'Piskent tumani'],
['id'=>156, 'region_id'=>12,	'name'=>'Parkent tumani'],
['id'=>157, 'region_id'=>12,	'name'=>'Ohangaron tumani'],
['id'=>158, 'region_id'=>12,	'name'=>'Ohangaron shahar'],
['id'=>159, 'region_id'=>12,	'name'=>'Olmaliq shahar'],
['id'=>160, 'region_id'=>12,	'name'=>'Oqqo‘rg‘on tumani'],
['id'=>161, 'region_id'=>12,	'name'=>'Qibray tumani'],
['id'=>162, 'region_id'=>12,	'name'=>'Zangiota tumani'],
['id'=>163, 'region_id'=>12,	'name'=>'Bo‘ka tuman'],
['id'=>164, 'region_id'=>12,	'name'=>'Bo‘stonliq tumani'],
['id'=>165, 'region_id'=>12,	'name'=>'Bekobod tumani'],
['id'=>166, 'region_id'=>12,	'name'=>'Bekobod shahar'],
['id'=>167, 'region_id'=>12,	'name'=>'Angren shahar'],
['id'=>168, 'region_id'=>7,	'name'=>'Элликқалъа тумани'],
['id'=>169, 'region_id'=>7,	'name'=>'Шўманой тумани'],
['id'=>170, 'region_id'=>7,	'name'=>'Чимбой тумани'],
['id'=>171, 'region_id'=>7,	'name'=>'Хўжайли тумани'],
['id'=>172, 'region_id'=>7,	'name'=>'Тўрткўл тумани'],
['id'=>173, 'region_id'=>7,	'name'=>'Тахтакўпир тумани'],
['id'=>174, 'region_id'=>7,	'name'=>'Тахиатош тумани'],
['id'=>175, 'region_id'=>7,	'name'=>'Нукус шаҳар'],
['id'=>176, 'region_id'=>7,	'name'=>'Нукус тумани'],
['id'=>177, 'region_id'=>7,	'name'=>'Мўйноқ тумани'],
['id'=>178, 'region_id'=>7,	'name'=>'Қўнғирот тумани'],
['id'=>179, 'region_id'=>7,	'name'=>'Қораўзак тумани'],
['id'=>180, 'region_id'=>7,	'name'=>'Қонликўл тумани'],
['id'=>181, 'region_id'=>7,	'name'=>'Кегейли тумани'],
['id'=>182, 'region_id'=>7,	'name'=>'Бўзатов тумани'],
['id'=>183, 'region_id'=>7,	'name'=>'Беруний тумани'],
['id'=>184, 'region_id'=>7,	'name'=>'Амударё тумани'],
['id'=>185, 'region_id'=>10,	'name'=>'Сирдарё тумани'],
['id'=>186, 'region_id'=>10,	'name'=>'Ховос тумани'],
['id'=>187, 'region_id'=>10,	'name'=>'Гулистон тумани'],
['id'=>188, 'region_id'=>10,	'name'=>'Сардоба тумани'],
['id'=>189, 'region_id'=>10,	'name'=>'Баёвут тумани'],
['id'=>190, 'region_id'=>10,	'name'=>'Мирзабод тумани'],
['id'=>191, 'region_id'=>10,	'name'=>'Сайхунобод тумани'],
['id'=>192, 'region_id'=>10,	'name'=>'Оқолтин тумани'],
['id'=>193, 'region_id'=>10,	'name'=>'Ширин шахар'],
['id'=>194, 'region_id'=>10,	'name'=>'Янгиер шахар'],
['id'=>195, 'region_id'=>10,	'name'=>'Гулистон шахар'],
             ]);


        $xorazm=[
            ['name'=>'D.Bahodirov', 'email'=>'D.Bahodirov1@us.uz' , 'district_id'=>11	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
            ['name'=>'D.Kurambayev'	, 'email'=>'D.Kurambayev1@us.uz', 'district_id'=>11, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'D.Raxmonov'	, 'email'=>'D.Raxmonov1@us.uz'	, 'district_id'=>12	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'S.Saparboyev'	, 'email'=>'S.Saparboyev1@us.uz'	, 'district_id'=>12	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'J.Abdullayev'	, 'email'=>'J.Abdullayev1@us.uz'	, 'district_id'=>2	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'S.Polyazov'	, 'email'=>'S.Polyazov1@us.uz'	, 'district_id'=>2	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'S.Abdullayev'	, 'email'=>'S.Abdullayev1@us.uz'	, 'district_id'=>2	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'Н.Aминов'	, 'email'=>'Н.Aминов1@us.uz'	, 'district_id'=>6	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'Т.Нураддинов'	, 'email'=>'Т.Нураддинов1@us.uz'	, 'district_id'=>6	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'И.Файзуллайев'	, 'email'=>'И.Файзуллайев1@us.uz'	, 'district_id'=>6	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'M.Yo‘ldashov'	, 'email'=>'M.Yo‘ldashov1@us.uz'	, 'district_id'=>10	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'R.Bekchanov'	, 'email'=>'R.Bekchanov1@us.uz'	, 'district_id'=>10	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'I.G‘ayibov'	, 'email'=>'I.G‘ayibov1@us.uz'	, 'district_id'=>10	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'A.Матяқубов'	, 'email'=>'A.Матяқубов1@us.uz'	, 'district_id'=>4	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'Ф.Сулайманов'	, 'email'=>'Ф.Сулайманов1@us.uz'	, 'district_id'=>4	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'Д.Фозилов'	, 'email'=>'Д.Фозилов1@us.uz'	, 'district_id'=>4	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'ДостонКаримов'	, 'email'=>'ДостонКаримов1@us.uz'	, 'district_id'=>12	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'М.Жумабоев'	, 'email'=>'М.Жумабоев1@us.uz'	, 'district_id'=>5	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'М.Хайитов'	, 'email'=>'М.Хайитов1@us.uz'	, 'district_id'=>5	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'Б.Атохонов'	, 'email'=>'Б.Атохонов1@us.uz'	, 'district_id'=>5	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'M.Sapayozov'	, 'email'=>'M.Sapayozov1@us.uz'	, 'district_id'=>13	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'I.Rajabov'	, 'email'=>'I.Rajabov1@us.uz'	, 'district_id'=>13	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'О.Собиров'	, 'email'=>'О.Собиров1@us.uz'	, 'district_id'=>13	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'О.Xаджайев'	, 'email'=>'О.Xаджайев1@us.uz'	, 'district_id'=>8	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'Б.Матсапайев'	, 'email'=>'Б.Матсапайев1@us.uz'	, 'district_id'=>8	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'O.Iskandarov'	, 'email'=>'O.Iskandarov1@us.uz'	, 'district_id'=>1	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'J.Yuldashov'	, 'email'=>'J.Yuldashov1@us.uz'	, 'district_id'=>1	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'I.Quramboyev'	, 'email'=>'I.Quramboyev1@us.uz'	, 'district_id'=>1	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'Р.Матчанов'	, 'email'=>'Р.Матчанов1@us.uz'	, 'district_id'=>2	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'Ж.Рахимов'	, 'email'=>'Ж.Рахимов1@us.uz'	, 'district_id'=>2	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'Ҳ.Рўзимбайев'	, 'email'=>'Ҳ.Рўзимбайев1@us.uz'	, 'district_id'=>2	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'М.Xусаинов'	, 'email'=>'М.Xусаинов1@us.uz'	, 'district_id'=>7	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'М.Мухаммадов'	, 'email'=>'М.Мухаммадов1@us.uz'	, 'district_id'=>7	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'R.Abdurahimov'	, 'email'=>'R.Abdurahimov1@us.uz'	, 'district_id'=>9	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'N.Sadullayev'	, 'email'=>'N.Sadullayev1@us.uz'	, 'district_id'=>9	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'R.Jabbergenov'	, 'email'=>'R.Jabbergenov1@us.uz'	, 'district_id'=>9	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
['name'=>'JumaboyevXumoyun'	, 'email'=>'JumaboyevXumoyun1@us.uz'	, 'district_id'=>11	, 'region_id'=>13, 'password'=>bcrypt('tuman'),'role'=>4],
            ['name'=>'AlimovAbdurohid'	,'email'=>'AlimovAbdurohid1@us.uz',	'district_id'=>71, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'IslomovDavlatbek'	,'email'=>'IslomovDavlatbek1@us.uz',	'district_id'=>71, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'IslomovBegzod'	,'email'=>'IslomovBegzod1@us.uz',	'district_id'=>71, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'MusurmonovSherzod'	,'email'=>'MusurmonovSherzod1@us.uz',	'district_id'=>70, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'To\'laganovSardor'	,'email'=>'TolaganovSardor1@us.uz',	'district_id'=>70, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'OmonovHusniddin'	,'email'=>'OmonovHusniddin1@us.uz',	'district_id'=>69, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'OltiboyevFurqat'	,'email'=>'OltiboyevFurqat1@us.uz',	'district_id'=>69, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'QushmurotovOdiljon'	,'email'=>'QushmurotovOdiljon1@us.uz',	'district_id'=>67, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'BahramovLaziz'	,'email'=>'BahramovLaziz1@us.uz',	'district_id'=>67, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'MuzrabovNo\'monjon'	,'email'=>'MuzrabovNomonjon1@us.uz',	'district_id'=>67, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'IsaqulovO\'tkir'	,'email'=>'IsaqulovOtkir1@us.uz',	'district_id'=>66, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'TursunovMurodjon'	,'email'=>'TursunovMurodjon1@us.uz',	'district_id'=>66, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'IlashboyevSamandar'	,'email'=>'IlashboyevSamandar1@us.uz',	'district_id'=>66, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'BobobekovKomil'	,'email'=>'BobobekovKomil1@us.uz',	'district_id'=>65, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'ErgashevJahongir'	,'email'=>'ErgashevJahongir1@us.uz',	'district_id'=>65, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'XolmurodovBozorboy'	,'email'=>'XolmurodovBozorboy1@us.uz',	'district_id'=>65, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'SindorovJasurbek'	,'email'=>'SindorovJasurbek1@us.uz',	'district_id'=>64, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'YuldashevAzizjon'	,'email'=>'YuldashevAzizjon1@us.uz',	'district_id'=>64, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'OlimjonovHamidjon'	,'email'=>'OlimjonovHamidjon1@us.uz',	'district_id'=>64, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'KasimovaOzoda'	,'email'=>'KasimovaOzoda1@us.uz',	'district_id'=>63, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'MurotqulovMuslimbek'	,'email'=>'MurotqulovMuslimbek1@us.uz',	'district_id'=>63, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'NazarqulovDilshodbek'	,'email'=>'NazarqulovDilshodbek1@us.uz',	'district_id'=>63, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'Jo\'raqulovShahzod'	,'email'=>'JoraqulovShahzod1@us.uz',	'district_id'=>69, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4], ['name'=>'MirzayevSardor'	,'email'=>'MirzayevSardor1@us.uz',	'district_id'=>73, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'RustamovShuhrat'	,'email'=>'RustamovShuhrat1@us.uz',	'district_id'=>73, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'NarzullayevNurbek'	,'email'=>'NarzullayevNurbek1@us.uz',	'district_id'=>73, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'MahmudovAbdulla'	,'email'=>'MahmudovAbdulla1@us.uz',	'district_id'=>74, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'QuchqarovAbdumalik'	,'email'=>'QuchqarovAbdumalik1@us.uz',	'district_id'=>74, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'DehqonovDilshod'	,'email'=>'DehqonovDilshod1@us.uz',	'district_id'=>74, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'XudoyqulovXurshid'	,'email'=>'XudoyqulovXurshid1@us.uz',	'district_id'=>72, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'IsmatovAkbar'	,'email'=>'IsmatovAkbar1@us.uz',	'district_id'=>72, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'DavronovJasur'	,'email'=>'DavronovJasur1@us.uz',	'district_id'=>72, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'AbdualimovAkbar'	,'email'=>'AbdualimovAkbar1@us.uz',	'district_id'=>177, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'XoliqovXudoyberdi'	,'email'=>'XoliqovXudoyberdi1@us.uz',	'district_id'=>177, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],
['name'=>'ShermamatovBegzod'	,'email'=>'ShermamatovBegzod1@us.uz',	'district_id'=>177, 'region_id'=>4, 'password'=>bcrypt('tuman'), 'role'=>4],


       ];
        $role_id=Role::all()->where('id',4)->first();
        foreach ($xorazm as $data){
            User::create($data)->assignRole([$role_id->id]);
        }

    }
}
